config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: 'games#index'

  devise_for :researchers, controllers: { registrations: 'registrations' }

  resources :games do
    resources :evaluations, only: %i(new create index show)
  end
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/evaluation.rb
# frozen_string_literal: true

class Evaluation < ApplicationRecord
  belongs_to :game
  validates :r1, :r2, :r3, :r4, :r5, :r6, :r7, :r8, :r9, :r10, :r11, :r12, :r13, :r14, :r15, :r16, :r17, :r18, :r19, :r20, :r21, :r22, presence: true
end

app/models/game.rb
# frozen_string_literal: true

class Game < ApplicationRecord
  has_many :evaluations
  validates :name, :description, :link, :how_to_play, presence: true

  NOT_RATED = 0

  def funcionality_dimension
    (easy_of_use_factor * factors_weight[:easy_of_use]) + (content_quality_factor * factors_weight[:content_quality])
  end

  def efficiency_dimension
    (versatility_factor * factors_weight[:versatility]) + (pedagogical_aspects_factor * factors_weight[:pedagogical_aspects]) + (didactical_resources_factor * factors_weight[:didactical_resources]) + (stimulates_the_initiative_and_self_learning_factor * factors_weight[:stimulates_the_initiative_and_self_learning])
  end

  def adaptability_dimension
    (audiovisual_quality_factor * factors_weight[:audiovisual_quality]) + (technical_and_static_elements_factor * factors_weight[:technical_and_static_elements]) + (navigation_and_interaction_factor * factors_weight[:navigation_and_interaction])
  end

  def euclidean_distance
    (1 - (funcionality_dimension / 100)) + (1 - (efficiency_dimension / 100)) + (1 - (adaptability_dimension / 100))
  end

  def system_quality
    ((1 - (euclidean_distance / Math.sqrt(10))) * 100)
  end

  def easy_of_use_factor
    calculate_questions(evaluations.pluck(:r1, :r2)) * (1.0 / 20)
  end

  def content_quality_factor
    calculate_questions(evaluations.pluck(:r8, :r9, :r10, :r11, :r12)) * (1.0 / 50)
  end

  def versatility_factor
    calculate_questions(evaluations.pluck(:r3, :r4, :r5, :r18)) * (1.0 / 40)
  end

  def pedagogical_aspects_factor
    calculate_questions([evaluations.pluck(:r19)]) * (1.0 / 10)
  end

  def didactical_resources_factor
    calculate_questions(evaluations.pluck(:r20, :r21)) * (1.0 / 20)
  end

  def stimulates_the_initiative_and_self_learning_factor
    calculate_questions([evaluations.pluck(:r22)]) * (1.0 / 10)
  end

  def audiovisual_quality_factor
    calculate_questions([evaluations.pluck(:r6)]) * (1.0 / 10)
  end

  def technical_and_static_elements_factor
    calculate_questions([evaluations.pluck(:r7)]) * (1.0 / 10)
  end

  def navigation_and_interaction_factor
    calculate_questions(evaluations.pluck(:r13, :r14, :r15, :r16)) * (1.0 / 40)
  end

  private

  def percentage
    {}.tap do |p|
      p['1'] = 0
      p['2'] = 25
      p['3'] = 50
      p['4'] = 75
      p['5'] = 100
    end
  end

  def factors_weight
    {}.tap do |factor|
      factor[:easy_of_use] = 0.5
      factor[:content_quality] = 0.5
      factor[:versatility] = 0.47
      factor[:pedagogical_aspects] = 0.14
      factor[:didactical_resources] = 0.25
      factor[:stimulates_the_initiative_and_self_learning] = 0.14
      factor[:audiovisual_quality] = 0.33
      factor[:technical_and_static_elements] = 0.33
      factor[:navigation_and_interaction] = 0.34
    end
  end

  def calculate_questions(questions)
    return NOT_RATED if questions.empty?
    questions.map { |question| (question.map { |q| percentage[q.to_s] }.compact.sum.to_f / evaluations.count) }.reduce(&:+) * 10
  end
end

app/models/researcher.rb
# frozen_string_literal: true

class Researcher < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
# frozen_string_literal: true

require 'application_responder'

class ApplicationController < ActionController::Base
  self.responder = ApplicationResponder
  respond_to :html

  protect_from_forgery with: :exception
end

app/controllers/evaluations_controller.rb
# frozen_string_literal: true

class EvaluationsController < ApplicationController
  before_action :set_evaluation, only: %i(show edit update destroy)
  before_action :set_game, only: %i(show index)

  def index; end

  def show; end

  def new
    @evaluation = Evaluation.new
    @game = Game.find params[:game_id]
  end

  def create
    @evaluation = Evaluation.new(evaluation_params)
    @evaluation.game_id = params[:game_id]
    @evaluation.save
    redirect_to game_evaluation_path(@evaluation.game_id, @evaluation.id)
  end

  private

  def set_game
    @game = Game.find params[:game_id]
  end

  def set_evaluation
    @evaluation = Evaluation.find(params[:id])
    @game = Game.find(@evaluation.game_id)
  end

  def evaluation_params
    params.require(:evaluation)
          .permit(:r1, :r2, :r3, :r4, :r5, :r6, :r7, :r8, :r9, :r10, :r11, :r12,
                  :r13, :r14, :r15, :r16, :r17, :r18, :r19, :r20, :r21, :r22, :game_id)
  end
end

app/controllers/games_controller.rb
# frozen_string_literal: true

class GamesController < ApplicationController
  before_action :authenticate_researcher!
  before_action :set_game, only: %i(show edit update destroy)

  respond_to :html

  def index
    @games = Game.all
    respond_with(@games)
  end

  def show
    respond_with(@game)
  end

  def new
    @game = Game.new
    respond_with(@game)
  end

  def edit; end

  def create
    @game = Game.new(game_params)
    @game.save
    respond_with(@game)
  end

  def update
    @game.update(game_params)
    respond_with(@game)
  end

  def destroy
    @game.destroy
    respond_with(@game)
  end

  private

  def set_game
    @game = Game.find(params[:id])
  end

  def game_params
    params.require(:game).permit(:name, :description, :link, :how_to_play, :easy_of_use, :content_quality, :versatility, :pedagogical_aspects, :didactical_resources, :stimulates_the_initiative_and_self_learning, :audiovisual_quality, :technical_and_static_elements, :navigation_and_interaction, :originality_and_use_of_advanced_tecnology)
  end
end

app/controllers/registrations_controller.rb
# frozen_string_literal: true

class RegistrationsController < Devise::RegistrationsController
  private

    def sign_up_params
      params.require(:researcher).permit(:name, :email, :password, :password_confirmation)
    end

    def account_update_params
      params.require(:researcher).permit(:name, :email, :password, :password_confirmation, :current_password)
    end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/evaluations_helper.rb
# frozen_string_literal: true

module EvaluationsHelper
end

app/helpers/games_helper.rb
# frozen_string_literal: true

module GamesHelper
end

app/views/evaluations/_evaluation_chart.html.erb
<script type="text/javascript" charset="utf-8">

google.charts.load('current', {packages: ['corechart']});
google.charts.setOnLoadCallback(drawBasic);

function drawBasic() {

  var data = new google.visualization.DataTable();
  var data = new google.visualization.DataTable();
  data.addColumn('number', 'Dimensões');
  data.addColumn('number', 'Funcionalidade');
  data.addColumn('number', 'Eficiencia');
  data.addColumn('number', 'Adaptabilidade');

  data.addRows([
    [1,  0, 0, 0],
    [2, <%= game.funcionality_dimension %>, <%= game.efficiency_dimension %>, <%= game.adaptability_dimension %>]
  ]);


  var options = {
    title: 'Qualidade por Dimensão',
    series: {
      0: {targetAxisIndex: 0},
      1: {targetAxisIndex: 1}
    },
    hAxis: {
      title: 'Pontos'
    },
    vAxis: {
      title: '%'
    }
  };

  var chart = new google.visualization.LineChart(document.getElementById('chart_div'));

  chart.draw(data, options);
}
</script>

app/views/evaluations/_form.html.erb
<%= form_for([@game, evaluation]) do |f| %>
  <div class="field">
    <%= f.label :r1 %>
    <%= f.radio_button :r1, '1' %>
    <%= f.label :r1_1, '1' %>
    <%= f.radio_button :r1, '2' %>
    <%= f.label :r1_2, '2' %>
    <%= f.radio_button :r1,'3' %>
    <%= f.label :r1_3, '3' %>
    <%= f.radio_button :r1, '4' %>
    <%= f.label :r1_4, '4' %>
    <%= f.radio_button :r1, '5' %>
    <%= f.label :r1_5, '5' %>
  </div>

  <div class="field">
    <%= f.label :r2 %>
    <%= f.radio_button :r2, '1' %>
    <%= f.label :r2_1, '1' %>
    <%= f.radio_button :r2, '2' %>
    <%= f.label :r2_2, '2' %>
    <%= f.radio_button :r2,'3' %>
    <%= f.label :r2_3, '3' %>
    <%= f.radio_button :r2, '4' %>
    <%= f.label :r2_4, '4' %>
    <%= f.radio_button :r2, '5' %>
    <%= f.label :r2_5, '5' %>
  </div>

  <div class="field">
    <%= f.label :r3 %>
    <%= f.radio_button :r3, '1' %>
    <%= f.label :r3_1, '1' %>
    <%= f.radio_button :r3, '2' %>
    <%= f.label :r3_2, '2' %>
    <%= f.radio_button :r3,'3' %>
    <%= f.label :r3_3, '3' %>
    <%= f.radio_button :r3, '4' %>
    <%= f.label :r3_4, '4' %>
    <%= f.radio_button :r3, '5' %>
    <%= f.label :r3_5, '5' %>
  </div>

  <div class="field">
    <%= f.label :r4 %>
    <%= f.radio_button :r4, '1' %>
    <%= f.label :r4_1, '1' %>
    <%= f.radio_button :r4, '2' %>
    <%= f.label :r4_2, '2' %>
    <%= f.radio_button :r4,'3' %>
    <%= f.label :r4_3, '3' %>
    <%= f.radio_button :r4, '4' %>
    <%= f.label :r4_4, '4' %>
    <%= f.radio_button :r4, '5' %>
    <%= f.label :r4_5, '5' %>
  </div>

  <div class="field">
    <%= f.label :r5 %>
    <%= f.radio_button :r5, '1' %>
    <%= f.label :r5_1, '1' %>
    <%= f.radio_button :r5, '2' %>
    <%= f.label :r5_2, '2' %>
    <%= f.radio_button :r5,'3' %>
    <%= f.label :r5_3, '3' %>
    <%= f.radio_button :r5, '4' %>
    <%= f.label :r5_4, '4' %>
    <%= f.radio_button :r5, '5' %>
    <%= f.label :r5_5, '5' %>
  </div>

  <div class="field">
    <%= f.label :r6 %>
    <%= f.radio_button :r6, '1' %>
    <%= f.label :r6_1, '1' %>
    <%= f.radio_button :r6, '2' %>
    <%= f.label :r6_2, '2' %>
    <%= f.radio_button :r6,'3' %>
    <%= f.label :r6_3, '3' %>
    <%= f.radio_button :r6, '4' %>
    <%= f.label :r6_4, '4' %>
    <%= f.radio_button :r6, '5' %>
    <%= f.label :r6_5, '5' %>
  </div>

  <div class="field">
    <%= f.label :r7 %>
    <%= f.radio_button :r7, '1' %>
    <%= f.label :r7_1, '1' %>
    <%= f.radio_button :r7, '2' %>
    <%= f.label :r7_2, '2' %>
    <%= f.radio_button :r7,'3' %>
    <%= f.label :r7_3, '3' %>
    <%= f.radio_button :r7, '4' %>
    <%= f.label :r7_4, '4' %>
    <%= f.radio_button :r7, '5' %>
    <%= f.label :r7_5, '5' %>
  </div>

  <div class="field">
    <%= f.label :r8 %>
    <%= f.radio_button :r8, '1' %>
    <%= f.label :r8_1, '1' %>
    <%= f.radio_button :r8, '2' %>
    <%= f.label :r8_2, '2' %>
    <%= f.radio_button :r8,'3' %>
    <%= f.label :r8_3, '3' %>
    <%= f.radio_button :r8, '4' %>
    <%= f.label :r8_4, '4' %>
    <%= f.radio_button :r8, '5' %>
    <%= f.label :r8_5, '5' %>
  </div>

  <div class="field">
    <%= f.label :r9 %>
    <%= f.radio_button :r9, '1' %>
    <%= f.label :r9_1, '1' %>
    <%= f.radio_button :r9, '2' %>
    <%= f.label :r9_2, '2' %>
    <%= f.radio_button :r9,'3' %>
    <%= f.label :r9_3, '3' %>
    <%= f.radio_button :r9, '4' %>
    <%= f.label :r9_4, '4' %>
    <%= f.radio_button :r9, '5' %>
    <%= f.label :r9_5, '5' %>
  </div>

  <div class="field">
    <%= f.label :r10 %>
    <%= f.radio_button :r10, '1' %>
    <%= f.label :r10_1, '1' %>
    <%= f.radio_button :r10, '2' %>
    <%= f.label :r10_2, '2' %>
    <%= f.radio_button :r10,'3' %>
    <%= f.label :r10_3, '3' %>
    <%= f.radio_button :r10, '4' %>
    <%= f.label :r10_4, '4' %>
    <%= f.radio_button :r10, '5' %>
    <%= f.label :r10_5, '5' %>
  </div>

  <div class="field">
    <%= f.label :r11 %>
    <%= f.radio_button :r11, '1' %>
    <%= f.label :r11_1, '1' %>
    <%= f.radio_button :r11, '2' %>
    <%= f.label :r11_2, '2' %>
    <%= f.radio_button :r11,'3' %>
    <%= f.label :r11_3, '3' %>
    <%= f.radio_button :r11, '4' %>
    <%= f.label :r11_4, '4' %>
    <%= f.radio_button :r11, '5' %>
    <%= f.label :r11_5, '5' %>
  </div>

  <div class="field">
    <%= f.label :r12 %>
    <%= f.radio_button :r12, '1' %>
    <%= f.label :r12_1, '1' %>
    <%= f.radio_button :r12, '2' %>
    <%= f.label :r12_2, '2' %>
    <%= f.radio_button :r12,'3' %>
    <%= f.label :r12_3, '3' %>
    <%= f.radio_button :r12, '4' %>
    <%= f.label :r12_4, '4' %>
    <%= f.radio_button :r12, '5' %>
    <%= f.label :r12_5, '5' %>
  </div>

  <div class="field">
    <%= f.label :r13 %>
    <%= f.radio_button :r13, '1' %>
    <%= f.label :r13_1, '1' %>
    <%= f.radio_button :r13, '2' %>
    <%= f.label :r13_2, '2' %>
    <%= f.radio_button :r13,'3' %>
    <%= f.label :r13_3, '3' %>
    <%= f.radio_button :r13, '4' %>
    <%= f.label :r13_4, '4' %>
    <%= f.radio_button :r13, '5' %>
    <%= f.label :r13_5, '5' %>
  </div>

  <div class="field">
    <%= f.label :r14 %>
    <%= f.radio_button :r14, '1' %>
    <%= f.label :r14_1, '1' %>
    <%= f.radio_button :r14, '2' %>
    <%= f.label :r14_2, '2' %>
    <%= f.radio_button :r14,'3' %>
    <%= f.label :r14_3, '3' %>
    <%= f.radio_button :r14, '4' %>
    <%= f.label :r14_4, '4' %>
    <%= f.radio_button :r14, '5' %>
    <%= f.label :r14_5, '5' %>
  </div>

  <div class="field">
    <%= f.label :r15 %>
    <%= f.radio_button :r15, '1' %>
    <%= f.label :r15_1, '1' %>
    <%= f.radio_button :r15, '2' %>
    <%= f.label :r15_2, '2' %>
    <%= f.radio_button :r15,'3' %>
    <%= f.label :r15_3, '3' %>
    <%= f.radio_button :r15, '4' %>
    <%= f.label :r15_4, '4' %>
    <%= f.radio_button :r15, '5' %>
    <%= f.label :r15_5, '5' %>
  </div>

  <div class="field">
    <%= f.label :r16 %>
    <%= f.radio_button :r16, '1' %>
    <%= f.label :r16_1, '1' %>
    <%= f.radio_button :r16, '2' %>
    <%= f.label :r16_2, '2' %>
    <%= f.radio_button :r16,'3' %>
    <%= f.label :r16_3, '3' %>
    <%= f.radio_button :r16, '4' %>
    <%= f.label :r16_4, '4' %>
    <%= f.radio_button :r16, '5' %>
    <%= f.label :r16_5, '5' %>
  </div>

  <div class="field">
    <%= f.label :r17 %>
    <%= f.radio_button :r17, '1' %>
    <%= f.label :r17_1, '1' %>
    <%= f.radio_button :r17, '2' %>
    <%= f.label :r17_2, '2' %>
    <%= f.radio_button :r17,'3' %>
    <%= f.label :r17_3, '3' %>
    <%= f.radio_button :r17, '4' %>
    <%= f.label :r17_4, '4' %>
    <%= f.radio_button :r17, '5' %>
    <%= f.label :r17_5, '5' %>
  </div>

  <div class="field">
    <%= f.label :r18 %>
    <%= f.radio_button :r18, '1' %>
    <%= f.label :r18_1, '1' %>
    <%= f.radio_button :r18, '2' %>
    <%= f.label :r18_2, '2' %>
    <%= f.radio_button :r18,'3' %>
    <%= f.label :r18_3, '3' %>
    <%= f.radio_button :r18, '4' %>
    <%= f.label :r18_4, '4' %>
    <%= f.radio_button :r18, '5' %>
    <%= f.label :r18_5, '5' %>
  </div>

  <div class="field">
    <%= f.label :r19 %>
    <%= f.radio_button :r19, '1' %>
    <%= f.label :r19_1, '1' %>
    <%= f.radio_button :r19, '2' %>
    <%= f.label :r19_2, '2' %>
    <%= f.radio_button :r19,'3' %>
    <%= f.label :r19_3, '3' %>
    <%= f.radio_button :r19, '4' %>
    <%= f.label :r19_4, '4' %>
    <%= f.radio_button :r19, '5' %>
    <%= f.label :r19_5, '5' %>
  </div>

  <div class="field">
    <%= f.label :r20 %>
    <%= f.radio_button :r20, '1' %>
    <%= f.label :r20_1, '1' %>
    <%= f.radio_button :r20, '2' %>
    <%= f.label :r20_2, '2' %>
    <%= f.radio_button :r20,'3' %>
    <%= f.label :r20_3, '3' %>
    <%= f.radio_button :r20, '4' %>
    <%= f.label :r20_4, '4' %>
    <%= f.radio_button :r20, '5' %>
    <%= f.label :r20_5, '5' %>
  </div>

  <div class="field">
    <%= f.label :r21 %>
    <%= f.radio_button :r21, '1' %>
    <%= f.label :r21_1, '1' %>
    <%= f.radio_button :r21, '2' %>
    <%= f.label :r21_2, '2' %>
    <%= f.radio_button :r21,'3' %>
    <%= f.label :r21_3, '3' %>
    <%= f.radio_button :r21, '4' %>
    <%= f.label :r21_4, '4' %>
    <%= f.radio_button :r21, '5' %>
    <%= f.label :r21_5, '5' %>
  </div>

  <div class="field">
    <%= f.label :r22 %>
    <%= f.radio_button :r22, '1' %>
    <%= f.label :r22_1, '1' %>
    <%= f.radio_button :r22, '2' %>
    <%= f.label :r22_2, '2' %>
    <%= f.radio_button :r22,'3' %>
    <%= f.label :r22_3, '3' %>
    <%= f.radio_button :r22, '4' %>
    <%= f.label :r22_4, '4' %>
    <%= f.radio_button :r22, '5' %>
    <%= f.label :r22_5, '5' %>
  </div>

  <div class="actions">
    <%= f.submit 'Salvar Avaliação', class: 'waves-light btn' %>
  </div>
<% end %>

app/views/evaluations/index.html.erb
<div class="container center">
  <h3>Evaluations: <%= @game.name %></h3>
</div>
<div class="container">
  <table>
    <thead>
      <th>Requisito</th>
      <th>Nota</th>
    </thead>
    <tbody>
      <tr>
        <td>Dimensão de Qualidade</td>
        <td><%= @game.funcionality_dimension.nan? ? ' - ' : @game.funcionality_dimension.round(2) %>%</td>
      </tr>
      <tr>
        <td>Dimensão de Eficiência</td>
        <td><%= @game.efficiency_dimension.nan? ? ' - ' : @game.efficiency_dimension.round(2) %>%</td>
      </tr>
      <tr>
        <td>Dimensão de Adaptabilidade</td>
        <td><%= @game.adaptability_dimension.nan? ? ' - ' : @game.adaptability_dimension.round(2) %>%</td>
      </tr>
      <tr>
        <td>Distância Euclidiana</td>
        <td><%= @game.euclidean_distance.nan? ? ' - ' : @game.euclidean_distance.round(2) %></td>
      </tr>
      <tr>
        <td>Qualidade do Sistema</td>
        <td><%= @game.system_quality.nan? ? ' - ' : @game.system_quality.round(2) %>%</td>
      </tr>
    </tbody>
  </table>
</div>
<br />
<div id="chart_div"></div>

<div class="container center">
  <%= link_to 'New Evaluation', new_game_evaluation_path, class: 'waves-effect waves-light btn' %>
</div>

<%= render partial: 'evaluation_chart', locals: { game: @game } %>

app/views/evaluations/new.html.erb
<h1>New Evaluation</h1>

<%= render 'form', evaluation: @evaluation %>

<div class="container center">
  <%= link_to 'Back', game_evaluations_path, class: 'waves-light btn' %>
</div>

app/views/games/_game.html.erb
<li>
  <div class="collapsible-header"><i class="material-icons">games</i><%= game.name %></div>
  <div class="collapsible-body">
    <div class="container center">
      <h5><%= game.description %></h5>
      <%= link_to game.link %>
    </div>
    <div class="container">
      <table>
        <thead>
          <th>Requisito</th>
          <th>Nota</th>
        </thead>
        <tbody>
          <tr>
            <td>Qualidade do Sistema</td>
            <td><%= game.system_quality.nan? ? ' - ' : game.system_quality.round(2) %>%</td>
          </tr>
        </tbody>
      </table>
    </div>
    <br />
    <div class="container">
      <div class= "row center">
      <%= link_to 'Detalhes', game, class: 'waves-effect waves-light btn' %>
      <%= link_to 'Avaliação', game_evaluations_path(game.id), class: 'waves-effect waves-light btn' %>
      <%= link_to 'Edit', edit_game_path(game), class: 'waves-effect waves-light btn' %>
      <%= link_to 'Destroy', game, method: :delete, data: { confirm: 'Are you sure?' }, class: 'waves-effect waves-red btn' %>
      </div>
    </div>
  </div>
</li>

app/views/games/edit.html.erb
<h1>Editing Game</h1>

<%= render 'form', game: @game %>

<div class="container center">
  <%= link_to 'Show', @game, class: 'waves-light btn' %>
  <%= link_to 'Back', games_path, class: 'waves-light btn' %>
</div>

app/views/games/index.html.erb
<div class="container center">
  <h3>Games</h3>
</div>

<ul class="collapsible popout" data-collapsible="accordion">
  <% @games.each do |game| %>
    <%= render partial: game %>
  <% end %>
</ul>

<br>

<div class="container center">
  <%= link_to 'Cadastrar Jogo', new_game_path, class: 'waves-effect waves-light btn' %>
</div>

<script type="text/javascript" charset="utf-8">
  $(document).ready(function(){
   $('.collapsible').collapsible();
  });
</script>

app/views/games/new.html.erb
<h1>New Game</h1>

<%= render 'form', game: @game %>

<div class="container center">
  <%= link_to 'Back', games_path, class: 'waves-light btn' %>
</div>

app/views/games/show.html.erb
<div class="row">
  <h4>Detalhes do Jogo</h4>
  <hr />
</div>
<div class="container">
  <div class="row">
    <strong>Name:</strong>
    <%= @game.name %>
  </div>

  <div class="row">
    <strong>Description:</strong>
    <%= @game.description %>
  </div>

  <div class="row">
    <strong>Link:</strong>
    <%= link_to @game.link %>
  </div>

  <div class="row">
    <strong>How to Play:</strong>
    <%= @game.how_to_play%>
  </div>
</div>

<div class="row">
  <h4>Peso dos Fatores</h4>
  <hr />
</div>

<div class="container">
  <div class="row">
    <h5> Dominio de Funcionalidade </h5>
  <table>
    <thead>
      <th>Fator</th>
      <th>Peso</th>
    </thead>
    <tbody>
      <tr>
        <td>Easy of use</td>
        <td><%= @game.easy_of_use %></td>
      </tr>
      <tr>
        <td>Content Quality</td>
        <td><%= @game.content_quality %></td>
      </tr>
    </tbody>
  </table>
  </div>
</div>
<br />

<div class="container">
  <div class="row">
    <h5> Dominio de Eficiência</h5>
    <table>
      <thead>
        <th>Fator</th>
        <th>Peso</th>
      </thead>
      <tbody>
        <tr>
          <td>Versatility</td>
          <td><%= @game.versatility %></td>
        </tr>
        <tr>
          <td>Pedagogical aspects</td>
          <td><%= @game.pedagogical_aspects %></td>
        </tr>
        <tr>
          <td>Didactical resources</td>
          <td><%= @game.didactical_resources %></td>
        </tr>
        <tr>
          <td>Stimulates the initiative and self learning</td>
          <td><%= @game.stimulates_the_initiative_and_self_learning %></td>
        </tr>
      </tbody>
    </table>
  </div>
</div>
<br />

<div class="container">
  <div class="row">
    <h5>Domínio de Adaptabilidade</h5>
    <table>
      <thead>
        <th>Fator</th>
        <th>Peso</th>
      </thead>
      <tbody>
        <tr>
          <td>Audiovisual quality</td>
          <td><%= @game.audiovisual_quality %></td>
        </tr>
        <tr>
          <td>Technical and static elements</td>
          <td><%= @game.technical_and_static_elements %></td>
        </tr>
        <tr>
          <td>Navigation and interaction</td>
          <td><%= @game.navigation_and_interaction %></td>
        </tr>
     </tbody>
    </table>
  </div>
</div>

<div class="container center">
  <%= link_to 'Edit', edit_game_path(@game), class:'waves-light btn' %>
  <%= link_to 'Back', games_path, class:'waves-light btn' %>
</div>

app/views/layouts/_topbar.html.erb
<ul id="dropdown1" class="dropdown-content">
  <li><%= link_to 'Novo Jogo', new_game_path if current_researcher %></li>
  <li><%= link_to 'Meus Jogos', root_path if current_researcher %></li>
  <li><%= link_to 'Meus Dados', edit_researcher_registration_path if current_researcher %></li>
  <li class="divider"></li>
  <li><%= link_to 'Logout', destroy_researcher_session_path, 'data-method': 'delete' if current_researcher %></li>
</ul>
<nav class="blue darken-2">
  <div class="nav-wrapper">
    <%= link_to 'Game Evaluation', root_path, class: 'brand-logo center' %>
    <ul class="right hide-on-med-and-down">
      <div class="user-dropdown">
        <li>
          <a class="dropdown-button" data-activates="dropdown1">
            <%= current_researcher.name || current_researcher.email if current_researcher %>
            <i class="material-icons right">arrow_drop_down</i>
          </a>
        </li>
      </div>
    </ul>
  </div>
</nav>

<script type="text/javascript" charset="utf-8">
$(document).ready(function(){
    $(".dropdown-button").dropdown()
})
</script>